version: "3.8"
services:
  db26:
    image: 'alexandrganitev/mifiib23ag:mysql'
    container_name: db26
    command: '--init-file /data/application/init.sql'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: instruments
    volumes:
      - './dbfile:/var/lib/mysql'
      - './init.sql:/data/application/init.sql'
    ports:
      - '3306:3306'
    restart: 'always'
  php-apache-server:
    image: 'alexandrganitev/mifiib23ag:ganitev2'
    container_name: php-apache-m26
    ports:
      - '8080:80'
    volumes:
      - './php:/var/www/html'
    depends_on:
      - db26
  mysqlclient_ag:
    image: 'alexandrganitev/mifiib23ag:mysqlclient_ag'
    container_name: mysqlclient_ag
    volumes:
      - './dbfile:/var/lib/mysql'
    tty: true
    depends_on:
      - db26


