shopping_center = ("Галерея", "Санкт-Петербург", "Лиговский пр., 30", ["H&M", "Zara"])
print("Кортеж до изменения:", shopping_center)
list_id_before = id(shopping_center[-1])
print("Идентификатор кортежа:", id(shopping_center))
print("Идентификатор списка в кортеже:", id(shopping_center[-1]))
shopping_center[-1].append("Uniqlo")
print("Кортеж после изменения:", shopping_center)
list_id_after = id(shopping_center[-1])
print("Идентификатор кортежа:", id(shopping_center))
print("Идентификатор списка в кортеже:", id(shopping_center[-1]))
print("Oбъекты, на которые ссылаются переменные равны (operator ==)?", list_id_before == list_id_after)
print("Две переменные указывают на один и тот же объект (operator is)?", list_id_before is list_id_after)