apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1-deployment
  labels:
    app: webapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: webapp1
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 80
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql-url
---

apiVersion: v1
kind: Service
metadata:
  name: webapp1-service
spec:
  type: NodePort
  selector:
    app: webapp1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30180